backend/models/Hotels.php
<?php

namespace backend\models;

use Yii;
use common\models\Languages;
use common\models\HotelsDescriptions;
use common\models\HotelsImages;
use common\models\ServioTranslates;
use backend\models\Features;
use yii\helpers\ArrayHelper;
use common\models\HotelsFeatures;
use common\models\GalleryImages;

/**
 * This is the model class for table "servio_hotels".
 *
 * @property integer $id
 * @property integer $cityId
 * @property string $alias
 * @property integer $serverId
 * @property integer $servioId
 * @property integer $tourTax
 * @property string $manager_emails
 * @property string $latitude
 * @property string $longitude
 * @property integer $visible
 * @property integer $rating
 */
class Hotels extends \common\models\Hotels {

    /**
     * Save hotel descrioptions to db
     * @return boolean
     */
    public function saveDescr()
    {
        $langs = Languages::getLangs();

        // save
        foreach($langs as $code => $lang) {
            // Skip empty description

            if(!empty($this->title[$code])) {

                // find descr
                $model = HotelsDescriptions::findOne([
                        'hotel_id' => $this->id,
                        'lang_id' => $lang['id'],
                ]);

                if(empty($model)) {
                    // new entry
                    $model = new HotelsDescriptions();
                }

                // Descr properties
                $model->hotel_id         = $this->id;
                $model->lang_id          = $lang['id'];
                $model->title            = $this->title[$code];
                $model->h1               = $this->h1[$code];
                $model->description      = $this->description[$code];
                $model->meta_description = $this->meta_description[$code];
                $model->address          = $this->address[$code];
                $model->map              = $this->map[$code];

                // Slug
                if(!empty($this->slug[$code])) {
                    $model->detachBehavior('slug');
                    $model->slug = $this->slug[$code];
                }

                if(!$model->save()) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Load hotel description to the model
     * @return boolean
     */
    public function hotelDescr()
    {
        $langs = Languages::getLangs();
        foreach($langs as $code => $lang) {
            // Get hotel description
            $descr = $this->getDescr($code)->one();

            // Assign properties
            if(!empty($descr)) {
                $this->title[$code]            = $descr->title;
                $this->h1[$code]               = $descr->h1;
                $this->description[$code]      = $descr->description;
                $this->meta_description[$code] = $descr->meta_description;
                $this->address[$code]          = $descr->address;
                $this->slug[$code]             = $descr->slug;
                $this->map[$code]              = $descr->map;
            }
        }
        return true;
    }

    /**
     * Get hotel name from servio module
     * @return mixed $name the hotel name
     */
    public function hotelName()
    {
        // model
        $model = ServioTranslates::findOne([
                'parentId' => $this->id,
                'parentType' => 'hotels',
                'isoLang' => 'ru',
        ]);

        if(!empty($model)) {
            $name = $model->name;
        } else {
            $name = null;
        }

        return $name;
    }

    public function hotelCity()
    {
        // model
        $model = ServioTranslates::findOne([
                'parentId' => $this->cityId,
                'parentType' => 'cities',
                'isoLang' => 'ru',
        ]);

        if(!empty($model)) {
            $name = $model->name;
        } else {
            $name = null;
        }

        return $name;
    }

    /**
     * Save image
     * @param type $image
     * @param type $main
     * @return boolean
     */
    public function saveImage($image, $main = 0)
    {
        $imageInfo = pathinfo($image);
        $suffix    = '';
        $i         = 1;
        do {
            // Search image in DB
            $fileName = $imageInfo['filename']
                . $suffix . '.' . $imageInfo['extension'];
            $search   = HotelsImages::find()
                ->where(['image' => $fileName])
                ->exists();
            $suffix   = '-' . $i++;
        } while($search);

        $filePath = 'images/hotels/' . $fileName;
        // Copy file to images/hotels
        if(copy(Yii::getAlias('@backend/web' . $image), $filePath)) {
            // search exist image
            $model = HotelsImages::findOne([
                    'hotel_id' => $this->id,
                    'main' => $main,
            ]);

            if(empty($model)) {
                // New image
                $model = new HotelsImages();
            }

            // load properties
            $model->hotel_id = $this->id;
            $model->image    = $fileName;
            $model->main     = $main;
            if($model->save()) {
                return $model->id;
            }
        }
        return false;
    }

    /**
     * Features available for hotel
     * @return array $features The hotel features 
     */
    public function featuresList()
    {
        $model = Features::find()
            ->select('{{features}}.id as id, {{features_descriptions}}.title as title')
            ->joinWith('descr')
            ->where([
                'status' => Features::FEATURES_STATUS_ACTIVE,
                'type' => Features::FEATURES_TYPE_HOTEL
            ])
            ->asArray()
            ->all();

        $features = ArrayHelper::map($model, 'id', 'title');
        return $features;
    }

    /**
     * Save hotels features
     * @return boolean
     */
    public function saveFeatures()
    {
        // Clean features
        if(HotelsFeatures::deleteAll(['hotel_id' => $this->id]) !== null) {
            if(!empty($this->hotelFeatures)) {
                // Add features
                foreach($this->hotelFeatures as $feature) {
                    $model             = new HotelsFeatures();
                    $model->hotel_id   = $this->id;
                    $model->feature_id = $feature;
                    if(!$model->save()) {
                        Yii::error('Error save hotels feature');
                        return false;
                    }
                }
            }
            return true;
        } else {
            Yii::error('Error clean hotels features');
            return false;
        }
    }

    public function hotelFeatures()
    {
        //$features = [];
        // Get faetures
        $features = HotelsFeatures::find()
            ->where(['hotel_id' => $this->id])
            ->asArray()
            ->all();

        return ArrayHelper::map($features, 'feature_id', 'feature_id');
    }
    
    /**
     * Save gallery images
     * @return boolean
     */
    public function saveImages()
    {
        $images = explode(', ', $this->images);
        foreach($images as $image) {
            $imageInfo = pathinfo($image);
            $directory = 'images/gallery/' . $this->id;
            $filePath  = $directory  . '/' . $imageInfo['basename'];
            
            // Create directory
            @mkdir($directory, 0777, true);

            // Copy file to images/gallery
            if(!copy(Yii::getAlias('@backend/web' . $image), $filePath)) {
                return false;
            }

            // Search image in DB
            $modelImage = GalleryImages::findOne([
                    'image' => $imageInfo['basename'],
                    'gallery_id' => $this->id
            ]);

            if($modelImage == null) {
                // Save image name to gallery_images
                $modelImage             = new GalleryImages();
                $modelImage->gallery_id = $this->id;
                $modelImage->image      = $imageInfo['basename'];
                $modelImage->type      = GalleryImages::GALLERY_TYPE_HOTEL;
                
                if(!$modelImage->save()) {
                    return false;
                }
            }
            
        }
        return true;
    }

}

backend/controllers/HotelsController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Hotels;
use backend\models\search\HotelsSearch;
use common\models\Languages;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\filters\AccessRule;
use common\models\GalleryImages;

/**
 * HotelsController implements the CRUD actions for Hotels model.
 */
class HotelsController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'rules' => [
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['index',],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Hotels models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new HotelsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Hotels model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing Hotels model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if($model->load(Yii::$app->request->post())) {
            // Save description
            if(!$model->saveDescr()) {
                throw new BadRequestHttpException('Ошибка сохранения описания отеля');
            }

            // Save images
            if(!empty($model->image)) {
                if(!$model->saveImage($model->image, 1)) {
                    Yii::warning('Ошибка сохранения изображения');
                }
            }
            if(!empty($model->images)) {
                if(!$model->saveImages()) {
                    Yii::warning('Ошибка сохранения галереи');
                }
            }

            // Save hotel
            if(!$model->save()) {
                Yii::warning($model->errors);
                throw new BadRequestHttpException('Ошибка сохранения отеля');
            }
            
            // Save features
            if(!$model->saveFeatures()) {
                throw new BadRequestHttpException('Ошибка сохранения характеристик');
            }
            

            return $this->redirect(['index']);
        } else {
            // Get langs
            $langs = Languages::getLangs();

            // Get hotel description
            $model->hotelDescr();
            
            // Get hotel features
            //$model->hotelFeatures();
            
            // Available features 
            $features = $model->featuresList();
            
            // Images
            $images = GalleryImages::getImages($model->id, GalleryImages::GALLERY_TYPE_HOTEL);

            return $this->render('update', [
                    'model' => $model,
                    'langs' => $langs,
                    'features' => $features,
                    'images' => $images,
            ]);
        }
    }

    /**
     * Deletes an existing Hotels model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Hotels model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Hotels the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        $model = Hotels::find()
            ->where(['{{servio_hotels}}.id' => $id])
            ->one();
        
        if($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/HotelsController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Response;
use frontend\models\Hotels;
use frontend\models\Rooms;
use frontend\models\Gallery;
use yii\web\NotFoundHttpException;

class HotelsController extends \yii\web\Controller {

    public $bodyId;

    /**
     * Hotel page action
     */
    public function actionView($slug)
    {
        $this->bodyId = 'page-hotel';
        $request      = Yii::$app->request;
        $search       = $request->post('search');
        $roomsCount   = $request->post('roomsCount');

        $hotel = Hotels::getHotelBySlug($slug);
        if($hotel === null) {
            throw new NotFoundHttpException('Page not found');
        }

        // isTouristTax
        if(isset($search['isTouristTax']) && $search['isTouristTax']) {
            $isTouristTax = true;
        } else {
            $isTouristTax = false;
        }

        // Conference rooms
        $rooms = $hotel->getConfRooms();

        return $this->render('view', [
                'hotel' => $hotel,
                'rooms' => $rooms,
                'banners' => Gallery::getCarousel('hotel', $hotel->id),
                'params' => Hotels::roomsParams($hotel->id, $roomsCount, $search),
                'isTouristTax' => $isTouristTax,
        ]);
    }

    /**
     * Search Hotel (booking) action
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionHotelsSearch()
    {
        $this->bodyId = 'page-hotel';
        $request      = Yii::$app->request;
        $search       = $request->post('search');
        $roomsCount   = $request->post('roomsCount');

        if($search) {
            $hotel = Hotels::find()
                ->where('id = :id', [':id' => $search['hotelId']])
                ->one();

            $banners = Gallery::getCarousel('hotel', $hotel->id);

            // isTouristTax
            if(isset($search['isTouristTax']) && $search['isTouristTax']) {
                $isTouristTax = true;
            } else {
                $isTouristTax = false;
            }

            return $this->render('view', [
                    'hotel' => $hotel,
                    'params' => Hotels::roomsParams($hotel->id, $roomsCount, $search),
                    'banners' => $banners,
                    'isTouristTax' => $isTouristTax,
            ]);
        } else {
            throw new NotFoundHttpException('Page not found');
        }
    }

    public function actionRoomsFeatures($hotel)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        // Features
        $features = Rooms::getRoomsFeatures($hotel);
        return [$features];
    }

    public function actionRooms($id)
    {
        $this->bodyId = 'page-hotel';

        $hotel = Hotels::findOne($id);
        if($hotel === null) {
            throw new NotFoundHttpException('Page not found');
        }



        return $this->render('rooms', [
                'hotel' => $hotel,
                'params' => Hotels::roomsParams($hotel->id, null, null),
        ]);
    }

    /**
     * Hotels for hotels category page
     * @return string
     */
    public function actionList()
    {
        $cache = Yii::$app->cache;
        $lang  = Yii::$app->language;

        // Get hotels
        $hotels = $cache->get('hotelsList' . $lang);
        if($hotels === false) {
            $hotels = Hotels::getHotels(false);

            // Caching results 
            $cache->set('hotelsList' . $lang, $hotels, Hotels::HOTELS_CACHE_EXPIRATION);
        }

        return $this->renderPartial('list', ['hotels' => $hotels]);
    }

}

frontend/views/hotels/list.php
<?php
/**
 * Hotels list
 */

use yii\helpers\Url;
$i = 0;
?> 
<?php
foreach($hotels as $hotel) { ?>
    <div id="hotel<?php echo $i++ ?>" class="city-hotel">
        <div style="background-image: url(<?php echo $hotel['image'] ?>); background-size: inherit;"
             onclick="location.href = '<?php echo $hotel['url'] ?>'" class="hotel-image">
        <div class="wrapper color-overlay">
            <div>
                <div class="name">
                    <a href="<?php echo $hotel['url'] ?>" title="<?php echo $hotel['name'] ?>">
                        <?php echo $hotel['name'] ?>
                    </a>
                </div>
                <?php for($stars = 0; $stars < $hotel['rating']; $stars++) { ?>
                    <div class="stars">
                        <i class="material-icons">star</i>
                    </div>
                <?php } ?>
                <div class="city">
                    <?php echo $hotel['city'] ?>
                </div>
            </div>
        </div>
    </div >
        <div class="hotel-descr">
            <p class="hotel-text"><?=$hotel["text"];?></p>
            <p>
                <a href="<?php echo $hotel['url'] ?>" title="<?php echo Yii::t('app', 'Детальніше') ?>" class="button-more waves-effect waves-blue btn-flat" style="
    color: #2196f3;
    padding: 11px 0;
    margin: 7px 0;
    height: 55px;
    font-weight: 500;
    font-size: 1.15rem;
">
                    <span><?php echo Yii::t('app', 'Детальніше') ?></span>
                    <i hide-xs="" class="material-icons right">
                        keyboard_arrow_down
                    </i>
                </a>
                <?$tlId = $hotel["tl_id"];?>
                <? if ($tlId):?>
                    <a href="<?php echo Url::to(['/pages/reservation', 'hotel_id' => $tlId]) ?>"
                       class="waves-effect waves-light blue btn"
                       title="<?php echo Yii::t('app', 'Забронювати') ?>"
                       style="padding: 0 5px; margin-top: -5px;">
                        <?php echo Yii::t('app', 'Забронювати') ?>
                    </a>
                <?endif;?>
            </p>
    </div>
    </div>
<?php } ?>

frontend/views/hotels/rooms.php
<?php
/* @var $this yii\web\View */

use yii\widgets\Breadcrumbs;
use mp\bmicrodata\BreadcrumbsUtility;
use common\models\Languages;

// Title
if(empty($hotel->descr->title)) {
    $title = 'Hotel';
} else {
    $title = $hotel->descr->title;
}

// City  name
if(!empty($hotel->servioCity->name)) {
    $this->params['breadcrumbs'][] = [
        'label' => $hotel->servioCity->name,
        'url' => null
    ];
}

// Breadcrumbs
$this->title                   = $title;
$this->params['breadcrumbs'][] = [
    'label' => $this->title,
    'url' => ['hotels/view', 'slug' => $hotel->descr->slug]
];

// Meta title
$this->title = $title;

// h1
$h1 = $title;

// Meta Description
if(!empty($hotel->descr->meta_description)) {
    $this->registerMetaTag([
        'name' => 'description',
        'content' => $hotel->descr->meta_description
    ]);
}

$roomsJs = 'getRooms("'. $hotel->id . '", "'
    . Languages::getIsoCode(). '", "'. $params. '");';

$this->registerJs($roomsJs, $this::POS_END);
?>
<?php
echo Breadcrumbs::widget([
    'homeLink' => BreadcrumbsUtility::getHome(Yii::t('app', 'Головна'), Yii::$app->getHomeUrl()), // Link home page with microdata
    'links' => isset($this->params['breadcrumbs']) ? BreadcrumbsUtility::UseMicroData($this->params['breadcrumbs']) : [], // Get other links with microdata    
    'options' => [ // Set microdata for container BreadcrumbList     
        'id' => 'breadcrumbs',
        'class' => 'breadcrumb',
        'itemscope itemtype' => 'http://schema.org/BreadcrumbList'
    ],
]);
?>
<section id="main" class="valign-wrapper">
    <h1><?php echo $h1 ?></h1>
    <div class="preloader-wrapper active valign center-align">
        <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div><div class="gap-patch">
                <div class="circle"></div>
            </div><div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
</section>
<section id="rooms-container">
</section>